on:
  push:
    branches:
      - main

name: conan

jobs:
  push-pkg:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect --force

      - name: Run
        env:
          CONAN_LOGIN_USERNAME: overte
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        run: |
          conan remote add overte https://git.anotherfoxguy.com/api/packages/overte/conan
          conan export . --version 18.17.1 --user overte --channel stable
          conan upload libnode/18.17.1@overte/stable -r overte -c


  run-conan:
    runs-on: ${{ matrix.config.os }}
    needs: push-pkg
    strategy:
      fail-fast: true
      matrix:
        config:
          # - name: Ubuntu Debug
          #   os: ubuntu-latest
          #   conan-profile: ubuntu-debug
          #   pkg-version: 18.17.1
          - name: Ubuntu Release
            os: ubuntu-latest
            conan-profile: ubuntu-release
            pkg-version: 18.17.1

          # - name: Windows 2019 Debug
          #   os: windows-2019
          #   conan-profile: vs-2019-debug
          #   pkg-version: 18.17.1
          - name: Windows 2019 Release
            os: windows-2019
            conan-profile: vs-2019-release
            pkg-version: 18.17.1

    name: ${{ matrix.config.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Install Conan
        run: |
          pip install conan
          conan profile detect --force

      - name: Setup conan on ubuntu
        if: startsWith(matrix.config.os, 'ubuntu')
        run: |
          echo "tools.system.package_manager:mode = install" > ~/.conan2/global.conf
          echo "tools.system.package_manager:sudo = True" >> ~/.conan2/global.conf

      - name: Run
        env:
          CONAN_LOGIN_USERNAME: overte
          CONAN_PASSWORD: ${{ secrets.CONAN_PASSWORD }}
        run: |
          conan remote add overte https://git.anotherfoxguy.com/api/packages/overte/conan
          conan install --requires libnode/18.17.1@overte/stable -pr="./.conan-profiles/${{ matrix.config.conan-profile }}" -b missing
          conan upload libnode/18.17.1@overte/stable -r overte -c
